name: student_search_app
description: A Flutter app for searching and managing student information with Supabase integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase integration
  supabase_flutter: ^2.3.4
  
  # UI components
  cupertino_icons: ^1.0.6
  
  # HTTP and networking
  http: ^1.1.2
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Date formatting
  intl: ^0.19.0
  
  # Charts for analytics
  fl_chart: ^0.66.2
  
  # Image handling
  cached_network_image: ^3.3.1
  
  # URL launcher for external links
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
