import 'package:flutter/material.dart';

class AppColors {
  static const Color primary = Color(0xFF00838F);
  static const Color secondary = Color(0xFF0277BD);
  static const Color accent = Color(0xFF0288D1);
  static const Color buttonColor = Color(0xFF00796B);
  static const Color buttonHoverColor = Color(0xFF004D40);
  static const Color inputBorderColor = Color(0xFF81D4FA);
  static const Color tableHeaderColor = Color(0xFF0288D1);
  static const Color successColor = Colors.green;
  static const Color errorColor = Colors.red;
  static const Color warningColor = Color(0xFFFFC107);
  static const Color backgroundOverlay = Color(0xCCE0F7FA);
}

class AppTextStyles {
  static const TextStyle heading1 = TextStyle(
    color: AppColors.primary,
    fontSize: 30,
    fontWeight: FontWeight.w700,
  );

  static const TextStyle heading2 = TextStyle(
    color: AppColors.secondary,
    fontSize: 26,
    fontWeight: FontWeight.w600,
  );

  static const TextStyle heading3 = TextStyle(
    color: AppColors.accent,
    fontSize: 24,
    fontWeight: FontWeight.w500,
  );

  static const TextStyle bodyText = TextStyle(
    color: Colors.black87,
    fontSize: 16,
    fontWeight: FontWeight.w400,
  );

  static const TextStyle buttonText = TextStyle(
    color: Colors.white,
    fontSize: 16,
    fontWeight: FontWeight.w600,
  );

  static const TextStyle tableHeader = TextStyle(
    color: Colors.white,
    fontSize: 18,
    fontWeight: FontWeight.bold,
  );

  static const TextStyle tableSubHeader = TextStyle(
    color: Colors.white,
    fontSize: 16,
    fontWeight: FontWeight.bold,
  );

  static const TextStyle resultText = TextStyle(
    fontSize: 30,
    fontWeight: FontWeight.bold,
  );

  static const TextStyle statusText = TextStyle(
    fontSize: 50,
    fontWeight: FontWeight.bold,
  );
}

class AppSizes {
  static const double padding = 20.0;
  static const double smallPadding = 12.0;
  static const double largePadding = 25.0;
  static const double borderRadius = 12.0;
  static const double inputHeight = 50.0;
  static const double buttonHeight = 50.0;
}

class ApiConfig {
  // For local development
  static const String baseUrl = 'http://localhost:3000';
  
  // For production (replace with your Vercel URL)
  // static const String baseUrl = 'https://your-app.vercel.app';
  
  static const String searchEndpoint = '/api/search';
  static const String healthEndpoint = '/api/health';
}

class DemoData {
  static const Map<String, Map<String, dynamic>> students = {
    'G4001': {
      'name': 'Ahmed Mohamed',
      'student_code': 'G4001',
      'is_confirmed': true,
      // First Semester - September
      'first_sem_september_session1_attendance': 1,
      'first_sem_september_session1_question1': 2,
      'first_sem_september_session1_question2': 1,
      'first_sem_september_session1_quiz': 2,
      'first_sem_september_session2_attendance': 0,
      'first_sem_september_session2_question1': 1,
      'first_sem_september_session2_question2': 0,
      'first_sem_september_session2_quiz': 1,
      'first_sem_september_session3_attendance': 1,
      'first_sem_september_session3_question1': 2,
      'first_sem_september_session3_question2': 2,
      'first_sem_september_session3_quiz': 2,
      'first_sem_september_session4_attendance': 1,
      'first_sem_september_session4_question1': 1,
      'first_sem_september_session4_question2': 2,
      'first_sem_september_session4_quiz': 1,
      'first_sem_september_total_attendance': 3,
      'first_sem_september_total_questions': 11,
      'first_sem_september_total_quiz': 6,
      'first_sem_september_total_score': 20,
      // First Semester - October
      'first_sem_october_session1_attendance': 1,
      'first_sem_october_session1_question1': 2,
      'first_sem_october_session1_question2': 2,
      'first_sem_october_session1_quiz': 2,
      'first_sem_october_session2_attendance': 1,
      'first_sem_october_session2_question1': 1,
      'first_sem_october_session2_question2': 2,
      'first_sem_october_session2_quiz': 1,
      'first_sem_october_session3_attendance': 0,
      'first_sem_october_session3_question1': 0,
      'first_sem_october_session3_question2': 0,
      'first_sem_october_session3_quiz': 0,
      'first_sem_october_session4_attendance': 1,
      'first_sem_october_session4_question1': 2,
      'first_sem_october_session4_question2': 1,
      'first_sem_october_session4_quiz': 2,
      'first_sem_october_total_attendance': 3,
      'first_sem_october_total_questions': 8,
      'first_sem_october_total_quiz': 5,
      'first_sem_october_total_score': 16,
      // First Semester - November
      'first_sem_november_session1_attendance': 1,
      'first_sem_november_session1_question1': 2,
      'first_sem_november_session1_question2': 2,
      'first_sem_november_session1_quiz': 2,
      'first_sem_november_session2_attendance': 1,
      'first_sem_november_session2_question1': 2,
      'first_sem_november_session2_question2': 2,
      'first_sem_november_session2_quiz': 2,
      'first_sem_november_session3_attendance': 1,
      'first_sem_november_session3_question1': 2,
      'first_sem_november_session3_question2': 2,
      'first_sem_november_session3_quiz': 2,
      'first_sem_november_session4_attendance': 1,
      'first_sem_november_session4_question1': 2,
      'first_sem_november_session4_question2': 2,
      'first_sem_november_session4_quiz': 2,
      'first_sem_november_total_attendance': 4,
      'first_sem_november_total_questions': 16,
      'first_sem_november_total_quiz': 8,
      'first_sem_november_total_score': 28,
      // First Semester - December
      'first_sem_december_session1_attendance': 1,
      'first_sem_december_session1_question1': 2,
      'first_sem_december_session1_question2': 2,
      'first_sem_december_session1_quiz': 2,
      'first_sem_december_session2_attendance': 1,
      'first_sem_december_session2_question1': 2,
      'first_sem_december_session2_question2': 2,
      'first_sem_december_session2_quiz': 2,
      'first_sem_december_session3_attendance': 1,
      'first_sem_december_session3_question1': 2,
      'first_sem_december_session3_question2': 2,
      'first_sem_december_session3_quiz': 2,
      'first_sem_december_session4_attendance': 1,
      'first_sem_december_session4_question1': 2,
      'first_sem_december_session4_question2': 2,
      'first_sem_december_session4_quiz': 2,
      'first_sem_december_total_attendance': 4,
      'first_sem_december_total_questions': 16,
      'first_sem_december_total_quiz': 8,
      'first_sem_december_total_score': 28,
      // Second Semester - January
      'second_sem_january_session1_attendance': 1,
      'second_sem_january_session1_question1': 2,
      'second_sem_january_session1_question2': 2,
      'second_sem_january_session1_quiz': 2,
      'second_sem_january_session2_attendance': 1,
      'second_sem_january_session2_question1': 2,
      'second_sem_january_session2_question2': 2,
      'second_sem_january_session2_quiz': 2,
      'second_sem_january_session3_attendance': 1,
      'second_sem_january_session3_question1': 2,
      'second_sem_january_session3_question2': 1,
      'second_sem_january_session3_quiz': 2,
      'second_sem_january_session4_attendance': 1,
      'second_sem_january_session4_question1': 2,
      'second_sem_january_session4_question2': 2,
      'second_sem_january_session4_quiz': 2,
      'second_sem_january_total_attendance': 4,
      'second_sem_january_total_questions': 15,
      'second_sem_january_total_quiz': 8,
      'second_sem_january_total_score': 27,
      // Second Semester - February
      'second_sem_february_session1_attendance': 1,
      'second_sem_february_session1_question1': 2,
      'second_sem_february_session1_question2': 2,
      'second_sem_february_session1_quiz': 2,
      'second_sem_february_session2_attendance': 1,
      'second_sem_february_session2_question1': 2,
      'second_sem_february_session2_question2': 2,
      'second_sem_february_session2_quiz': 2,
      'second_sem_february_session3_attendance': 1,
      'second_sem_february_session3_question1': 2,
      'second_sem_february_session3_question2': 2,
      'second_sem_february_session3_quiz': 2,
      'second_sem_february_session4_attendance': 1,
      'second_sem_february_session4_question1': 2,
      'second_sem_february_session4_question2': 2,
      'second_sem_february_session4_quiz': 2,
      'second_sem_february_total_attendance': 4,
      'second_sem_february_total_questions': 16,
      'second_sem_february_total_quiz': 8,
      'second_sem_february_total_score': 28,
      // Second Semester - March
      'second_sem_march_session1_attendance': 1,
      'second_sem_march_session1_question1': 2,
      'second_sem_march_session1_question2': 2,
      'second_sem_march_session1_quiz': 2,
      'second_sem_march_session2_attendance': 1,
      'second_sem_march_session2_question1': 2,
      'second_sem_march_session2_question2': 2,
      'second_sem_march_session2_quiz': 2,
      'second_sem_march_session3_attendance': 1,
      'second_sem_march_session3_question1': 2,
      'second_sem_march_session3_question2': 2,
      'second_sem_march_session3_quiz': 2,
      'second_sem_march_session4_attendance': 1,
      'second_sem_march_session4_question1': 2,
      'second_sem_march_session4_question2': 2,
      'second_sem_march_session4_quiz': 2,
      'second_sem_march_total_attendance': 4,
      'second_sem_march_total_questions': 16,
      'second_sem_march_total_quiz': 8,
      'second_sem_march_total_score': 28,
      // Second Semester - April
      'second_sem_april_session1_attendance': 1,
      'second_sem_april_session1_question1': 2,
      'second_sem_april_session1_question2': 2,
      'second_sem_april_session1_quiz': 2,
      'second_sem_april_session2_attendance': 1,
      'second_sem_april_session2_question1': 2,
      'second_sem_april_session2_question2': 2,
      'second_sem_april_session2_quiz': 2,
      'second_sem_april_session3_attendance': 1,
      'second_sem_april_session3_question1': 2,
      'second_sem_april_session3_question2': 2,
      'second_sem_april_session3_quiz': 2,
      'second_sem_april_session4_attendance': 1,
      'second_sem_april_session4_question1': 2,
      'second_sem_april_session4_question2': 2,
      'second_sem_april_session4_quiz': 2,
      'second_sem_april_total_attendance': 4,
      'second_sem_april_total_questions': 16,
      'second_sem_april_total_quiz': 8,
      'second_sem_april_total_score': 28,
    },
    'G5001': {
      'name': 'Fatima Ali',
      'student_code': 'G5001',
      'is_confirmed': true,
      // September
      'september_session1_attendance': 1,
      'september_session1_question1': 2,
      'september_session1_question2': 1,
      'september_session1_quiz': 2,
      'september_session2_attendance': 1,
      'september_session2_question1': 1,
      'september_session2_question2': 2,
      'september_session2_quiz': 1,
      'september_session3_attendance': 1,
      'september_session3_question1': 2,
      'september_session3_question2': 2,
      'september_session3_quiz': 2,
      'september_session4_attendance': 1,
      'september_session4_question1': 1,
      'september_session4_question2': 1,
      'september_session4_quiz': 2,
      'september_total_attendance': 4,
      'september_total_questions': 11,
      'september_total_quiz': 7,
      'september_total_score': 22,
      // October
      'october_session1_attendance': 1,
      'october_session1_question1': 2,
      'october_session1_question2': 2,
      'october_session1_quiz': 2,
      'october_session2_attendance': 1,
      'october_session2_question1': 2,
      'october_session2_question2': 1,
      'october_session2_quiz': 2,
      'october_session3_attendance': 1,
      'october_session3_question1': 1,
      'october_session3_question2': 2,
      'october_session3_quiz': 1,
      'october_session4_attendance': 1,
      'october_session4_question1': 2,
      'october_session4_question2': 2,
      'october_session4_quiz': 2,
      'october_total_attendance': 4,
      'october_total_questions': 12,
      'october_total_quiz': 7,
      'october_total_score': 23,
      // November
      'november_session1_attendance': 1,
      'november_session1_question1': 2,
      'november_session1_question2': 2,
      'november_session1_quiz': 2,
      'november_session2_attendance': 1,
      'november_session2_question1': 2,
      'november_session2_question2': 2,
      'november_session2_quiz': 2,
      'november_session3_attendance': 1,
      'november_session3_question1': 1,
      'november_session3_question2': 2,
      'november_session3_quiz': 1,
      'november_session4_attendance': 1,
      'november_session4_question1': 2,
      'november_session4_question2': 2,
      'november_session4_quiz': 2,
      'november_total_attendance': 4,
      'november_total_questions': 13,
      'november_total_quiz': 7,
      'november_total_score': 24,
      // December
      'december_session1_attendance': 1,
      'december_session1_question1': 2,
      'december_session1_question2': 2,
      'december_session1_quiz': 2,
      'december_session2_attendance': 1,
      'december_session2_question1': 2,
      'december_session2_question2': 2,
      'december_session2_quiz': 2,
      'december_session3_attendance': 1,
      'december_session3_question1': 2,
      'december_session3_question2': 2,
      'december_session3_quiz': 2,
      'december_session4_attendance': 1,
      'december_session4_question1': 2,
      'december_session4_question2': 2,
      'december_session4_quiz': 2,
      'december_total_attendance': 4,
      'december_total_questions': 16,
      'december_total_quiz': 8,
      'december_total_score': 28,
    },
    'G6001': {
      'name': 'Omar Hassan',
      'student_code': 'G6001',
      'is_confirmed': false,
      // September
      'september_session1_attendance': 1,
      'september_session1_question1': 1,
      'september_session1_question2': 2,
      'september_session1_quiz': 1,
      'september_session2_attendance': 1,
      'september_session2_question1': 2,
      'september_session2_question2': 1,
      'september_session2_quiz': 2,
      'september_session3_attendance': 1,
      'september_session3_question1': 1,
      'september_session3_question2': 1,
      'september_session3_quiz': 1,
      'september_session4_attendance': 1,
      'september_session4_question1': 2,
      'september_session4_question2': 1,
      'september_session4_quiz': 1,
      'september_total_attendance': 4,
      'september_total_questions': 9,
      'september_total_quiz': 5,
      'september_total_score': 18,
      // October
      'october_session1_attendance': 1,
      'october_session1_question1': 2,
      'october_session1_question2': 2,
      'october_session1_quiz': 2,
      'october_session2_attendance': 1,
      'october_session2_question1': 1,
      'october_session2_question2': 2,
      'october_session2_quiz': 1,
      'october_session3_attendance': 1,
      'october_session3_question1': 2,
      'october_session3_question2': 2,
      'october_session3_quiz': 2,
      'october_session4_attendance': 1,
      'october_session4_question1': 1,
      'october_session4_question2': 2,
      'october_session4_quiz': 1,
      'october_total_attendance': 4,
      'october_total_questions': 11,
      'october_total_quiz': 6,
      'october_total_score': 21,
      // November
      'november_session1_attendance': 1,
      'november_session1_question1': 2,
      'november_session1_question2': 2,
      'november_session1_quiz': 2,
      'november_session2_attendance': 1,
      'november_session2_question1': 2,
      'november_session2_question2': 1,
      'november_session2_quiz': 2,
      'november_session3_attendance': 1,
      'november_session3_question1': 1,
      'november_session3_question2': 2,
      'november_session3_quiz': 1,
      'november_session4_attendance': 1,
      'november_session4_question1': 2,
      'november_session4_question2': 2,
      'november_session4_quiz': 2,
      'november_total_attendance': 4,
      'november_total_questions': 12,
      'november_total_quiz': 7,
      'november_total_score': 23,
      // December
      'december_session1_attendance': 1,
      'december_session1_question1': 2,
      'december_session1_question2': 2,
      'december_session1_quiz': 2,
      'december_session2_attendance': 1,
      'december_session2_question1': 2,
      'december_session2_question2': 2,
      'december_session2_quiz': 2,
      'december_session3_attendance': 1,
      'december_session3_question1': 2,
      'december_session3_question2': 1,
      'december_session3_quiz': 2,
      'december_session4_attendance': 1,
      'december_session4_question1': 2,
      'december_session4_question2': 2,
      'december_session4_quiz': 2,
      'december_total_attendance': 4,
      'december_total_questions': 13,
      'december_total_quiz': 8,
      'december_total_score': 25,
    },
    'P1001': {
      'name': 'Layla Ahmed',
      'student_code': 'P1001',
      'is_confirmed': true,
      // September
      'september_session1_attendance': 1,
      'september_session1_question1': 2,
      'september_session1_question2': 2,
      'september_session1_quiz': 2,
      'september_session2_attendance': 1,
      'september_session2_question1': 2,
      'september_session2_question2': 2,
      'september_session2_quiz': 2,
      'september_session3_attendance': 1,
      'september_session3_question1': 2,
      'september_session3_question2': 2,
      'september_session3_quiz': 2,
      'september_session4_attendance': 1,
      'september_session4_question1': 2,
      'september_session4_question2': 2,
      'september_session4_quiz': 2,
      'september_total_attendance': 4,
      'september_total_questions': 16,
      'september_total_quiz': 8,
      'september_total_score': 28,
      // October
      'october_session1_attendance': 1,
      'october_session1_question1': 2,
      'october_session1_question2': 2,
      'october_session1_quiz': 2,
      'october_session2_attendance': 1,
      'october_session2_question1': 2,
      'october_session2_question2': 2,
      'october_session2_quiz': 2,
      'october_session3_attendance': 1,
      'october_session3_question1': 2,
      'october_session3_question2': 2,
      'october_session3_quiz': 2,
      'october_session4_attendance': 1,
      'october_session4_question1': 2,
      'october_session4_question2': 2,
      'october_session4_quiz': 2,
      'october_total_attendance': 4,
      'october_total_questions': 16,
      'october_total_quiz': 8,
      'october_total_score': 28,
      // November
      'november_session1_attendance': 1,
      'november_session1_question1': 2,
      'november_session1_question2': 2,
      'november_session1_quiz': 2,
      'november_session2_attendance': 1,
      'november_session2_question1': 2,
      'november_session2_question2': 2,
      'november_session2_quiz': 2,
      'november_session3_attendance': 1,
      'november_session3_question1': 2,
      'november_session3_question2': 2,
      'november_session3_quiz': 2,
      'november_session4_attendance': 1,
      'november_session4_question1': 2,
      'november_session4_question2': 2,
      'november_session4_quiz': 2,
      'november_total_attendance': 4,
      'november_total_questions': 16,
      'november_total_quiz': 8,
      'november_total_score': 28,
      // December
      'december_session1_attendance': 1,
      'december_session1_question1': 2,
      'december_session1_question2': 2,
      'december_session1_quiz': 2,
      'december_session2_attendance': 1,
      'december_session2_question1': 2,
      'december_session2_question2': 2,
      'december_session2_quiz': 2,
      'december_session3_attendance': 1,
      'december_session3_question1': 2,
      'december_session3_question2': 2,
      'december_session3_quiz': 2,
      'december_session4_attendance': 1,
      'december_session4_question1': 2,
      'december_session4_question2': 2,
      'december_session4_quiz': 2,
      'december_total_attendance': 4,
      'december_total_questions': 16,
      'december_total_quiz': 8,
      'december_total_score': 28,
    },
  };
}
